apps/activities/urls.py
from django.conf.urls import url

from . import views


urlpatterns = [
    url(r'^$', views.ActivitiesView.as_view(), name='view'),
    url(r'^create/$', views.CreateActivityView.as_view(), name='create-activity'),
    url(r'^search/$', views.SearchActivitiesView.as_view(), name='search'),
    url(r'^search/(?P<uuid>\w+)/$', views.TagFilterView.as_view(), name='tag-filter'),
    url(r'^(?P<uuid>\w+)/$', views.ActivityView.as_view(), name='preview'),
    url(r'^(?P<uuid>\w+)/attendees/$', views.ActivityAttendeeView.as_view(), name='attendees'),
]

apps/pages/urls.py
from django.conf.urls import url

from . import views


urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
]

apps/users/urls.py
from django.conf.urls import url

from . import views


urlpatterns = [
    url(r'^register/$', views.RegisterView.as_view(), name='register'),
    url(r'^login/$', views.LoginView.as_view(), name='login'),
    url(r'^profile/$', views.SelfProfileView.as_view(), name='profile'),
    url(r'^profile/settings/$', views.ProfileSettingsView.as_view(), name='profile-settings'),
    url(r'^profile/(?P<uuid>\w+)/', views.ProfileView.as_view(), name='user-profile'),
    url(r'^logout/$', views.LogoutView.as_view(), name='logout'),
]

core/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^api/', include(('apps.api.urls', 'api'), namespace='api')),
    
    url(r'^admin/', admin.site.urls),
    
    url(r'^groups/', include(('apps.groups.urls', 'groups'), namespace='groups')),
    url(r'^users/', include(('apps.users.urls', 'users'), namespace='users')),
    url(r'^activities/', include(('apps.activities.urls', 'activities'), namespace='activities')),
    url(r'^m/', include(('apps.mobile.urls', 'mobile'), namespace='mobile')),
    url(r'', include(('apps.pages.urls', 'pages'), namespace='pages')),
    
]

templates/base/_base.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>

    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
    <link rel="stylesheet" href="/static/styles/style.css">

    {% if title %}
    <title>{{title}} | Gymder</title>
    {% else %}
    <title>Gymder</title>
    {% endif %}
</head>

<body>
    {% include '../base/navbar.html' %}
    {% block content %}
    {% endblock %}

    <script src="https://code.jquery.com/jquery-3.4.1.min.js" integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
    <script>

        var  csrf_token = '{{ csrf_token }}';
        {% if context %}
        var context = {{context|safe}}
        {% endif %}

        $(document).ready(function() {
            // here we initialize all materialize components required
            $('.dropdown-trigger').dropdown();
            $('.sidenav').sidenav();
            $('.tabs').tabs();
            M.updateTextFields();
        });
    </script>

    {% block scripts %}
    {% endblock  %}
</body>
</html>

templates/base/navbar.html
<ul id="profile-dropdown" class="dropdown-content">
    <li>
        <a href="{% url 'users:profile' %}">Profile</a>
    </li>
    <li>
        <a href="{% url 'users:profile-settings' %}">Settings</a>
    </li>
    <li>
        <a href="{% url 'users:logout' %}">Logout</a>
    </li>
</ul>

<ul class="sidenav" id="mobile-nav">
    <li>
        <a href="{% url 'pages:index' %}">Home</a>
    </li>
    {% if user.is_authenticated %}
        <li>
            <a href="{% url 'users:profile' %}">Profile</a>
        </li>
        <li>
            <a href="{% url 'groups:index' %}">Groups</a>
        </li>
        <li>
            <a href="{% url 'activities:view' %}">Activities</a>
        </li>
        <li>
            <a href="{% url 'users:logout' %}">Logout</a>
        </li>
    {% else %}
        <li>
            <a href="{% url 'users:register' %}">Register</a>
        </li>
        <li>
            <a href="{% url 'users:login' %}">Login</a>
        </li>
    {% endif %}
</ul>

<nav>
    <div class="nav-wrapper">
        <a href="/" class="brand-logo">Gymder</a>
        <a href="#" data-target="mobile-nav" class="sidenav-trigger">
            <i class="material-icons">menu</i>
        </a>

        <ul id="nav-mobile" class="right hide-on-med-and-down">
            <li>
                <a href="{% url 'pages:index' %}">Home</a>
            </li>
            {% if user.is_authenticated %}
                <li>
                    <a href="{% url 'groups:index' %}">Groups</a>
                </li>
                <li>
                    <a href="{% url 'activities:view' %}">Activities</a>
                </li>
                <li>
                    <a class="dropdown-trigger center" href="#!" data-target="profile-dropdown">
                        {{ user.email }} <i class="material-icons right">arrow_drop_down</i>
                    </a>
                </li>
            {% else %}
                <li>
                    <a href="{% url 'users:login' %}">Login</a>
                </li>
            {% endif %}
        </ul>
    </div>
</nav>